on:
  push:
    branches:
      - master

name: release

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          release-type: node
          package-name: hexo-theme-keep
          changelog-types: '[
            {
              "type": "feat",
              "section": "🌟 Features",
              "hidden": false
            },
            {
              "type": "fix",
              "section": "🐞 Bug Fixes",
              "hidden": false
            },
            {
              "type": "docs",
              "section": "📖 Docs",
              "hidden": false
            },
            {
              "type": "style",
              "section": "🎨 Styling",
              "hidden": false
            },
            {
              "type": "refactor",
              "section": "🍭 Code Refactoring",
              "hidden": false
            },
            {
              "type": "perf",
              "section": "🛠 Performance Improvements",
              "hidden": false
            },
            {
              "type": "test",
              "section": "🚧 Tests",
              "hidden": false
            },
            {
              "type": "build",
              "section": "📦 Build System",
              "hidden": false
            },
            {
              "type": "revert",
              "section": "🌀 Reverts",
              "hidden": false
            },
            {
              "type": "ci",
              "section": "🎯 CI",
              "hidden": false
            },
            {
              "type": "ui",
              "section": "💄 Improvement UI",
              "hidden": false
            },
            {
              "type": "chore",
              "section": "🚦 Chore",
              "hidden": false
            }
          ]'

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish --provenance
        if: ${{ steps.release.outputs.release_created }}
